export const TYPES = {
  ROOM_SUCCESS: 'ROOM_SUCCESS',
  ROOM_ERROR: 'ROOM_ERROR',
  ROOM_REQUEST: 'ROOM_REQUEST',
  SET_CURRENT_ROOM: 'SET_CURRENT_ROOM',
  ADD_USER_TO_ROOM: 'ADD_USER_TO_ROOM',
  PLAYER_VOTED: 'PLAYER_VOTED',
  SET_PLAYERS: 'SET_PLAYERS',
};
