export const TYPES = {
  ROOM_SUCCESS: 'ROOM_SUCCESS',
  ROOM_ERROR: 'ROOM_ERROR',
  ROOM_REQUEST: 'ROOM_REQUEST',
  SET_CURRENT_ROOM: 'SET_CURRENT_ROOM',
  SET_ROOMS: 'SET_ROOMS',
  USER_ACTION: 'USER_ACTION',
  PLAYER_VOTED: 'PLAYER_VOTED',
  SET_PLAYERS: 'SET_PLAYERS',
  CLEAR_VOTES: 'CLEAR_VOTES',
};
